package urbanizacion.view;

public class MenuUsuario extends javax.swing.JFrame {
    

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        facturas = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JButton();
        administracion = new javax.swing.JButton();
        ocupaVecinos = new javax.swing.JButton();
        administracionvalor = new javax.swing.JLabel();
        vecinosocupa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facturas.setText("Consultar Facturas");

        btnFacturas.setText("Facturas");
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });

        administracion.setText("Administración");
        administracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administracionActionPerformed(evt);
            }
        });

        ocupaVecinos.setText("Ocupación vecinos");
        ocupaVecinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocupaVecinosActionPerformed(evt);
            }
        });

        administracionvalor.setText("Consultar valor administración");

        vecinosocupa.setText("Consultar ocupación vecinos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFacturas)
                        .addGap(86, 86, 86)
                        .addComponent(administracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ocupaVecinos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facturas)
                        .addGap(42, 42, 42)
                        .addComponent(administracionvalor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(vecinosocupa)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(facturas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vecinosocupa)
                            .addComponent(administracionvalor))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacturas)
                    .addComponent(administracion)
                    .addComponent(ocupaVecinos))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Facturas facturas = new Facturas();
        facturas.setVisible(true);
        dispose();

    }                                           

    private void administracionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        ValorAdministracion valorAdmi = new ValorAdministracion();
        valorAdmi.setVisible(true);
        dispose();
    }                                              

    private void ocupaVecinosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        OcupacionVecinos ocupa = new OcupacionVecinos();
        ocupa.setVisible(true);
        dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton administracion;
    private javax.swing.JLabel administracionvalor;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JLabel facturas;
    private javax.swing.JButton ocupaVecinos;
    private javax.swing.JLabel vecinosocupa;
    // End of variables declaration                   
}